// <auto-generated />
using System;
using AlonePostponement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlonePostponement.Migrations
{
    [DbContext(typeof(AlonePostponementContext))]
    partial class AlonePostponementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlonePostponement.Models.AlonePostponement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("DateOfEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateOfGiven")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AlonePostponementDBS");
                });

            modelBuilder.Entity("AlonePostponement.Models.BrotherEill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllBrotherEill")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestReciveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestSendTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestStatuesIDReqStatuesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RequestStatuesIDReqStatuesID");

                    b.ToTable("BrotherEillDBS");
                });

            modelBuilder.Entity("AlonePostponement.Models.BrothersID", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrotherID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestReciveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestSendTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestStatuesIDReqStatuesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RequestStatuesIDReqStatuesID");

                    b.ToTable("BrothersIDDBS");
                });

            modelBuilder.Entity("AlonePostponement.Models.DeadBrothers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllDeadBrothers")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestReciveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestSendTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestStatuesIDReqStatuesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RequestStatuesIDReqStatuesID");

                    b.ToTable("DeadBrothersDBS");
                });

            modelBuilder.Entity("AlonePostponement.Models.HaveBrothers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HaveBrother")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestReciveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestSendTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestStatuesIDReqStatuesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RequestStatuesIDReqStatuesID");

                    b.ToTable("HaveBrothersDBS");
                });

            modelBuilder.Entity("AlonePostponement.Models.RequestStatues", b =>
                {
                    b.Property<int>("ReqStatuesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfDone")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRecive")
                        .HasColumnType("datetime2");

                    b.Property<string>("Statues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReqStatuesID");

                    b.ToTable("RequestStatuesDBS");
                });

            modelBuilder.Entity("AlonePostponement.Models.BrotherEill", b =>
                {
                    b.HasOne("AlonePostponement.Models.RequestStatues", "RequestStatuesID")
                        .WithMany()
                        .HasForeignKey("RequestStatuesIDReqStatuesID");

                    b.Navigation("RequestStatuesID");
                });

            modelBuilder.Entity("AlonePostponement.Models.BrothersID", b =>
                {
                    b.HasOne("AlonePostponement.Models.RequestStatues", "RequestStatuesID")
                        .WithMany()
                        .HasForeignKey("RequestStatuesIDReqStatuesID");

                    b.Navigation("RequestStatuesID");
                });

            modelBuilder.Entity("AlonePostponement.Models.DeadBrothers", b =>
                {
                    b.HasOne("AlonePostponement.Models.RequestStatues", "RequestStatuesID")
                        .WithMany()
                        .HasForeignKey("RequestStatuesIDReqStatuesID");

                    b.Navigation("RequestStatuesID");
                });

            modelBuilder.Entity("AlonePostponement.Models.HaveBrothers", b =>
                {
                    b.HasOne("AlonePostponement.Models.RequestStatues", "RequestStatuesID")
                        .WithMany()
                        .HasForeignKey("RequestStatuesIDReqStatuesID");

                    b.Navigation("RequestStatuesID");
                });
#pragma warning restore 612, 618
        }
    }
}
