// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostponementOfConvictsAPI.Data;

namespace PostponementOfConvictsAPI.Migrations
{
    [DbContext(typeof(PostponementOfConvictsContext))]
    [Migration("20230118102509_PostponementOfConvictsMIG")]
    partial class PostponementOfConvictsMIG
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.AsyncEntryDate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Entrydate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestReciveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestSendTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestStatuesIDReqStatuesID")
                        .HasColumnType("int");

                    b.Property<string>("Statues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RequestStatuesIDReqStatuesID");

                    b.ToTable("AsyncEntryDateDb");
                });

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.AsyncInJail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("InJail")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestReciveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestSendTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestStatuesIDReqStatuesID")
                        .HasColumnType("int");

                    b.Property<string>("Statues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RequestStatuesIDReqStatuesID");

                    b.ToTable("AsyncInJailDb");
                });

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.AsyncYearsRemaning", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("RequestReciveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestSendTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestStatuesIDReqStatuesID")
                        .HasColumnType("int");

                    b.Property<string>("Statues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Years")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RequestStatuesIDReqStatuesID");

                    b.ToTable("AsyncYearsRemaningDb");
                });

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.PostponementOfConvicts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("DateOfEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateOfGiven")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PostponementOfConvictsDb");
                });

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.RabbitMQResponce", b =>
                {
                    b.Property<int>("ProcID")
                        .HasColumnType("int");

                    b.Property<int>("RequestStatuseID")
                        .HasColumnType("int");

                    b.Property<string>("Responce")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("RabbitMQResponceDBS");
                });

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.RabbitMQobj", b =>
                {
                    b.Property<string>("JWT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcID")
                        .HasColumnType("int");

                    b.Property<int>("RequestStatuseID")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.ToTable("RabbitMQobjDBS");
                });

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.RequestStatues", b =>
                {
                    b.Property<int>("ReqStatuesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfDone")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRecive")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostponmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReqStatuesID");

                    b.ToTable("RequestStatuesDBS");
                });

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.UserInfo", b =>
                {
                    b.Property<string>("JWT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.ToTable("UserInfoDBS");
                });

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.AsyncEntryDate", b =>
                {
                    b.HasOne("PostponementOfConvictsAPI.Models.RequestStatues", "RequestStatuesID")
                        .WithMany()
                        .HasForeignKey("RequestStatuesIDReqStatuesID");

                    b.Navigation("RequestStatuesID");
                });

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.AsyncInJail", b =>
                {
                    b.HasOne("PostponementOfConvictsAPI.Models.RequestStatues", "RequestStatuesID")
                        .WithMany()
                        .HasForeignKey("RequestStatuesIDReqStatuesID");

                    b.Navigation("RequestStatuesID");
                });

            modelBuilder.Entity("PostponementOfConvictsAPI.Models.AsyncYearsRemaning", b =>
                {
                    b.HasOne("PostponementOfConvictsAPI.Models.RequestStatues", "RequestStatuesID")
                        .WithMany()
                        .HasForeignKey("RequestStatuesIDReqStatuesID");

                    b.Navigation("RequestStatuesID");
                });
#pragma warning restore 612, 618
        }
    }
}
