version: '3.4'

services:

  sql-server-db:
    container_name: SQL_Server2
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqlvol2:/var/opt/mssql
    ports:
      - "1404:1433"
    environment:
      SA_PASSWORD: "r00t.R00T"
      ACCEPT_EULA: "Y"

  consul:
    image: consul:latest
    container_name: consul_server2
    network_mode: bridge
    ports:
      - "8501:8500"
      - "8601:8600/udp"
    command:  consul agent -dev -server -ui -node=server-1 -bootstrap-expect=1 -client="0.0.0.0"

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /docker/uptimekuma:/app/data
    ports:
      - 3001:3001

  schoolpostponementapi:
    image: ${DOCKER_REGISTRY-}schoolpostponementapi
    build:
      context: .
      dockerfile: SchoolPostponementAPI/Dockerfile
    ports:
      - "61012:80"
      - "60012:443"

  travelapprovalapi:
    image: ${DOCKER_REGISTRY-}travelapprovalapi
    build:
      context: .
      dockerfile: TravelApprovalAPI/Dockerfile
    ports:
      - "61000:80"
      - "60000:443"

  cashallowanceapi:
    image: ${DOCKER_REGISTRY-}cashallowanceapi
    build:
      context: .
      dockerfile: CashAllowanceAPI/Dockerfile
    ports:
      - "61001:80"
      - "60001:443"

  cashallowanclessthan42:
    image: ${DOCKER_REGISTRY-}cashallowanclessthan42
    build:
      context: .
      dockerfile: CashAllowancLessThan42/Dockerfile
    ports:
      - "61002:80"
      - "60002:443"

  alonepostponement:
    image: ${DOCKER_REGISTRY-}alonepostponement
    build:
      context: .
      dockerfile: AlonePostponement/Dockerfile
    ports:
      - "61014:80"
      - "60014:443"

  brotherinservicepostponementapi:
    image: ${DOCKER_REGISTRY-}brotherinservicepostponementapi
    build:
      context: .
      dockerfile: BrotherInServicePostponementAPI/Dockerfile
    ports:
      - "61030:80"
      - "60030:443"

  loginapi:
    image: ${DOCKER_REGISTRY-}loginapi
    build:
      context: .
      dockerfile: LoginAPI/Dockerfile
    ports:
      - "61050:80"
      - "60050:443"


  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "61051:80"
      - "60051:443"

  fixedserviceallowanceapi:
    image: ${DOCKER_REGISTRY-}fixedserviceallowanceapi
    build:
      context: .
      dockerfile: FixedServiceAllowanceAPI/Dockerfile
    ports:
      - "51009:80"
      - "50009:443"

  postponementofconvictsapi:
    image: ${DOCKER_REGISTRY-}postponementofconvictsapi
    build:
      context: .
      dockerfile: PostponementOfConvictsAPI/Dockerfile

  obligatoryserviceapi:
    image: ${DOCKER_REGISTRY-}obligatoryserviceapi
    build:
      context: .
      dockerfile: ObligatoryServiceAPI/Dockerfile

  RabbitMQ:
    image: rabbitmq:3.9-management
    container_name: RabbitMQ
    ports:
      -  "5672:5672" 
      -  "15672:15672"


  userrequesthandler:
    image: ${DOCKER_REGISTRY-}userrequesthandler
    build:
      context: .
      dockerfile: UserRequestHandler/Dockerfile
    ports:
      - "61053:80"
      - "60053:443"

  externalapicaller:
    image: ${DOCKER_REGISTRY-}externalapicaller
    build:
      context: .
      dockerfile: ExternalAPICaller/Dockerfile
    ports:
      - "61052:80"
      - "60052:443"

  usertransactions:
    image: ${DOCKER_REGISTRY-}usertransactions
    build:
      context: .
      dockerfile: UserTransactions/Dockerfile
    ports:
      - "61054:80"
      - "60054:443"

volumes:
  sqlvol2:

